name: Update and Build Workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  UPSTREAM_REPO: "excalidraw/excalidraw"

jobs:
  check-releases:
    name: Check for new releases
    runs-on: ubuntu-latest

    steps:
    - name: Fetch latest release version
      id: upstream-release
      run: |
        upstream_release_tag=$(curl -sL https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/releases/latest | jq -r ".tag_name")
        echo "upstream_release_tag=$upstream_release_tag" >> $GITHUB_OUTPUT

    - name: Fetch latest upstream release body
      id: upstream-release-body
      run: |
        echo 'upstream_release_body<<EOF' >> $GITHUB_OUTPUT
        curl -sL https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/releases/latest | jq -r ".body" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT

    - name: Fetch latest local release version
      id: local-release
      run: |
        local_release_tag=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r ".tag_name")
        echo "local_release_tag=$local_release_tag" >> $GITHUB_OUTPUT

    - name: Compare release versions
      if: steps.upstream-release.outputs.upstream_release_tag != steps.local-release.outputs.local_release_tag
      id: compare-releases
      run: |
        curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o /tmp/semver2.sh
        chmod +x /tmp/semver2.sh
        compare_result=$(/tmp/semver2.sh \
          ${{ steps.upstream-release.outputs.upstream_release_tag }} \
          ${{ steps.local-release.outputs.local_release_tag }})
        echo "compare_result=$compare_result" >> $GITHUB_OUTPUT

    outputs:
      newReleaseFound: ${{ steps.compare-releases.outputs.compare_result }}
      upstreamReleaseTag: ${{ steps.upstream-release.outputs.upstream_release_tag }}
      upstreamReleaseBody: ${{ steps.upstream-release-body.outputs.upstream_release_body }}
